# Generated by Django 2.2.12 on 2021-06-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.ImageField(upload_to='songs'),
        ),
    ]
